"""Generate a docker-compose file for an N-node Ripple cluster.

    python docker/gen_compose.py --nodes 50 --racks 5 > docker/docker-compose.yml
    docker compose -f docker/docker-compose.yml up --build

Nodes are spread across simulated racks. Node 1 is the seed and the publisher;
everyone else joins through it and gossip does the rest -- no node needs a
complete peer list to start, which is the property that makes this deployable at
300 nodes rather than merely runnable at 3.

Written as a generator rather than a checked-in 50-service YAML file because the
node count is a variable of the experiment, and a hand-maintained file that long
would drift from the code the first time anything changed.
"""

from __future__ import annotations

import argparse

HEADER = """# GENERATED by docker/gen_compose.py -- do not edit by hand.
# %d nodes across %d racks, plus a dashboard.
name: ripple

services:
"""

NODE = """  %(name)s:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: >
      node --id %(name)s --port 7000 --rack %(rack)s
      --root /data%(seed)s%(extra)s --verbose
    networks: [ripple]
    volumes:
      - %(name)s-data:/data
%(depends)s
"""

DASH = """  dashboard:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: dash --peers %(peers)s --port 8080
    ports:
      - "%(port)d:8080"
    networks: [ripple]
    depends_on: [n001]
"""

FOOTER = """
networks:
  ripple:
    driver: bridge

volumes:
%s
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--nodes", type=int, default=50)
    ap.add_argument("--racks", type=int, default=5)
    ap.add_argument("--seeds", type=int, default=2,
                    help="how many seed nodes joiners are pointed at")
    ap.add_argument("--dash-port", type=int, default=8080)
    ap.add_argument("--publish", default="",
                    help="path inside the seed container to publish at startup")
    a = ap.parse_args()

    names = ["n%03d" % i for i in range(1, a.nodes + 1)]
    seeds = names[:a.seeds]
    out = [HEADER % (a.nodes, a.racks)]

    for i, name in enumerate(names):
        is_seed = name in seeds
        # A node must not list itself as a seed. Every other seed is fair game
        # for --seed: joining retries, so pointing two seeds at each other is
        # useful redundancy rather than a bootstrap problem.
        seed_targets = [s for s in seeds if s != name]
        seed = (" --seed " + ",".join("%s:7000" % s for s in seed_targets)) if seed_targets else ""
        extra = ""
        if is_seed and i == 0 and a.publish:
            extra = " --publish %s --publish-path /cluster/payload.bin" % a.publish

        # depends_on must be acyclic, so it only ever points *backwards* in the
        # node ordering. Mutual --seed entries would otherwise make the seed set
        # depend on itself and Compose would refuse to start at all.
        earlier = [s for s in seed_targets if names.index(s) < i]
        depends = ""
        if earlier:
            depends = "    depends_on:\n" + "".join("      - %s\n" % s for s in earlier)
        out.append(NODE % {"name": name, "rack": "rack%d" % (i % a.racks),
                           "seed": seed, "extra": extra, "depends": depends})

    # The dashboard polls a sample of nodes rather than all of them: at 300
    # containers, polling everything twice a second would make the dashboard the
    # busiest thing in the cluster.
    watched = names if len(names) <= 60 else names[::max(1, len(names) // 60)]
    out.append(DASH % {"peers": ",".join("%s:7000" % n for n in watched),
                       "port": a.dash_port})
    out.append(FOOTER % "".join("  %s-data:\n" % n for n in names))
    print("".join(out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
